### ISSUE TITLE
SDK crashes on incoming calls for Android

### ISSUE THREAD

**Issue by gulfpearl** [jefflinwood/twilio_client_phonegap#20]
When I recieve an incoming call, the app crashes, I get the following:

```
E/Parcel  (  953): Class not found when unmarshalling: com.twilio.client.impl.InternalConnectionImpl
E/Parcel  (  953): java.lang.ClassNotFoundException: com.twilio.client.impl.InternalConnectionImpl
E/Parcel  (  953): 	at java.lang.Class.classForName(Native Method)
E/Parcel  (  953): 	at java.lang.Class.forName(Class.java:251)
E/Parcel  (  953): 	at java.lang.Class.forName(Class.java:216)
E/Parcel  (  953): 	at android.os.Parcel.readParcelableCreator(Parcel.java:2133)
E/Parcel  (  953): 	at android.os.Parcel.readParcelable(Parcel.java:2097)
E/Parcel  (  953): 	at android.os.Parcel.readValue(Parcel.java:2013)
E/Parcel  (  953): 	at android.os.Parcel.readArrayMapInternal(Parcel.java:2314)
E/Parcel  (  953): 	at android.os.Bundle.unparcel(Bundle.java:249)
E/Parcel  (  953): 	at android.os.Bundle.getString(Bundle.java:1118)
E/Parcel  (  953): 	at android.content.Intent.getStringExtra(Intent.java:5285)
E/Parcel  (  953): 	at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1586)
E/Parcel  (  953): 	at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:1167)
E/Parcel  (  953): 	at com.android.server.am.ActivityManagerService.startActivityInPackage(ActivityManagerService.java:4786)
E/Parcel  (  953): 	at com.android.server.am.PendingIntentRecord.sendInner(PendingIntentRecord.java:254)
E/Parcel  (  953): 	at com.android.server.am.PendingIntentRecord.send(PendingIntentRecord.java:194)
E/Parcel  (  953): 	at android.content.IIntentSender$Stub.onTransact(IIntentSender.java:64)
E/Parcel  (  953): 	at android.os.Binder.execTransact(Binder.java:404)
E/Parcel  (  953): 	at dalvik.system.NativeStart.run(Native Method)
E/Parcel  (  953): Caused by: java.lang.NoClassDefFoundError: com/twilio/client/impl/InternalConnectionImpl
E/Parcel  (  953): 	... 18 more
E/Parcel  (  953): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.twilio.client.impl.InternalConnectionImpl" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/Parcel  (  953): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/Parcel  (  953): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/Parcel  (  953): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/Parcel  (  953): 	... 18 more
```
```
W/MessageQueue( 1262): Handler (android.media.MediaPlayer$EventHandler) {44313280} sending message to a Handler on a dead thread
W/MessageQueue( 1262): java.lang.RuntimeException: Handler (android.media.MediaPlayer$EventHandler) {44313280} sending message to a Handler on a dead thread
W/MessageQueue( 1262): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:320)
W/MessageQueue( 1262): 	at android.os.Handler.enqueueMessage(Handler.java:626)
W/MessageQueue( 1262): 	at android.os.Handler.sendMessageAtTime(Handler.java:595)
W/MessageQueue( 1262): 	at android.os.Handler.sendMessageDelayed(Handler.java:566)
W/MessageQueue( 1262): 	at android.os.Handler.sendMessage(Handler.java:503)
W/MessageQueue( 1262): 	at android.media.MediaPlayer.postEventFromNative(MediaPlayer.java:3407)
W/MessageQueue( 1262): 	at dalvik.system.NativeStart.run(Native Method)
V/MediaPlayer( 1262): back from callback
```

**Comment by jefflinwood** [comment]
Hi,

Thanks - it looks like it's not finding that Twilio class, I'll take a look at this.

**Comment by nickwaelkens** [comment]
Well that's weird. I had the exact same problem last Friday and when I tested it today, it works. Magic?

**Comment by gulfpearl** [comment]
Hi, have you had any luck with this? Is there something else I can supply to help figure out whats going wrong?

**Comment by gulfpearl** [comment]
This works now for me.

**Comment by tom367** [comment]
I seem to be still experiencing this problem, but only when receiving a call after a certain amount of time (~2-3 hours).
