### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by kalitk0** [jefflinwood/twilio_client_phonegap#47]
App crash on Samsung Galaxy S6 and on phones with 64 bit architecture

java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.spoof.call.international-1/base.apk"],nativeLibraryDirectories=[/data/app/com.spoof.call.international-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libtwilio-native.so"
	at java.lang.Runtime.loadLibrary(Runtime.java:366)
	at java.lang.System.loadLibrary(System.java:989)
	at com.twilio.client.impl.useragent.UserAgent.<clinit>(UserAgent.java:16)
	at com.twilio.client.impl.CallControlManager.initialize(CallControlManager.java:189)
	at com.twilio.client.impl.CallControlManager.getInstance(CallControlManager.java:131)
	at com.twilio.client.impl.TwilioClientServiceImpl.initialize(TwilioClientServiceImpl.java:169)
	at com.twilio.client.TwilioClientService.onCreate(TwilioClientService.java:50)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3286)
	at android.app.ActivityThread.access$1900(ActivityThread.java:182)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1558)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6141)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by jefflinwood** [comment]
Thanks - that appears to be a Twilio Client for Android issue - could you raise that as a support issue with Twilio directly? 

They'll have to release a new version of the SDK with native arm64 libraries. 

http://stackoverflow.com/questions/30805249/how-do-i-disable-an-android-service-for-certain-architectures
