### ISSUE TITLE
Execution failed for task ':processReleaseResources'.

### ISSUE THREAD

**Issue by mobileias** [jefflinwood/twilio_client_phonegap#84]
Hello 

I have try to build using phonegap cli 7.0.1

but build failed and it shows error log like

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.032 secs
Error: /project/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:font
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontStyle
ERROR: In <declare-styleable> FontFamilyFont, unable to find attribute android:fontWeight

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

So can you please help 

Thanks

**Comment by ghost** [comment]
Were you able to resolve this error?

**Comment by lyngbach** [comment]
I am getting similar issue when building on Cordova 7.1.0 and 6.4.0. It seems to somehow be connected with gradle throwing a Unhandled promise rejection. But when I remove the plugin I have no problem building on either version.

@sabanad I am currently stuck and cant get this plugin to work on 7.10 however on 6.4.0 I was able to successfully build when adding this to the bottom of ```platforms\android\build.gradle``` file:
```js
configurations.all {
    resolutionStrategy {
        force 'com.android.support:support-v4:27.1.0'
    }
}
```
Just be wary if you add this without a config plugin or alike if you decide to remove and add the platform again in the future.

**Comment by ishan123456789** [comment]
Consider this issue #86 My comment has your answer
